// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package data

import (
	"database/sql"
)

type SoundcloudPlaylist struct {
	ID           int64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	ExternalID   sql.NullInt64
	Name         sql.NullString
	SearchUrl    sql.NullString
	PermalinkUrl sql.NullString
}

type SoundcloudPlaylistTrack struct {
	SoundcloudTrackID    sql.NullInt64
	SoundcloudPlaylistID sql.NullInt64
}

type SoundcloudTrack struct {
	ID                  int64
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	ExternalID          sql.NullInt64
	Name                sql.NullString
	PermalinkUrl        sql.NullString
	PurchaseTitle       sql.NullString
	PurchaseUrl         sql.NullString
	HasDownloadsLeft    sql.NullBool
	Genre               sql.NullString
	ArtworkUrl          sql.NullString
	TagList             sql.NullString
	PublisherArtist     sql.NullString
	SoundCloudUser      sql.NullString
	LocalPath           sql.NullString
	LocalPathBroken     sql.NullBool
	RemovedFromPlaylist sql.NullBool
}
