package data

import (
	"context"
	"database/sql"
)

/*
Contains a series of functions used to interface with the queries generated by sqlc
for the purpose of processing multiple records at once
*/

func (sDB *SerenDB) TxUpsertSoundCloudPlaylistAndTracks(p SoundcloudPlaylist, tracks []SoundcloudTrack) error {
	tx, err := sDB.Begin()

	if err != nil {
		return err
	}
	defer tx.Rollback()

	qtx := sDB.Queries.WithTx(tx)

	insertedP, err := qtx.UpsertSoundCloudPlaylist(context.Background(), UpsertSoundCloudPlaylistParams{
		ExternalID: p.ExternalID,
		Name:       p.Name,
		SearchUrl:  p.SearchUrl,
		Permalink:  p.Permalink,
	})

	if err != nil {
		tx.Rollback()
		return err
	}

	for _, t := range tracks {
		insertedT, err := qtx.UpsertSoundCloudTrack(context.Background(), UpsertSoundCloudTrackParams{
			ExternalID:          t.ExternalID,
			Name:                t.Name,
			Permalink:           t.Permalink,
			PurchaseTitle:       t.PurchaseTitle,
			PurchaseUrl:         t.PurchaseUrl,
			HasDownloadsLeft:    t.HasDownloadsLeft,
			Genre:               t.Genre,
			ArtworkUrl:          t.ArtworkUrl,
			TagList:             t.TagList,
			PublisherArtist:     t.PublisherArtist,
			SoundCloudUser:      t.SoundCloudUser,
			LocalPath:           t.LocalPath,
			LocalPathBroken:     t.LocalPathBroken,
			RemovedFromPlaylist: t.RemovedFromPlaylist,
		})

		if err != nil {
			tx.Rollback()
			return err
		}

		_, err = qtx.UpsertSoundCloudPlaylistTrack(context.Background(), UpsertSoundCloudPlaylistTrackParams{
			SoundcloudPlaylistID: sql.NullInt64{Valid: true, Int64: insertedP.ID},
			SoundcloudTrackID:    sql.NullInt64{Valid: true, Int64: insertedT.ID},
		})

		if err != nil {
			tx.Rollback()
			return err
		}
	}

	tx.Commit()

	return nil
}

func (sDB *SerenDB) TxUpsertSoundCloudTracks(t []SoundcloudTrack) error {
	tx, err := sDB.Begin()

	if err != nil {
		return err
	}

	defer tx.Rollback()

	qtx := sDB.Queries.WithTx(tx)

	for _, t := range t {

		_, err := qtx.UpsertSoundCloudTrack(context.Background(), UpsertSoundCloudTrackParams{
			ExternalID:          t.ExternalID,
			Name:                t.Name,
			Permalink:           t.Permalink,
			PurchaseTitle:       t.PurchaseTitle,
			PurchaseUrl:         t.PurchaseUrl,
			HasDownloadsLeft:    t.HasDownloadsLeft,
			Genre:               t.Genre,
			ArtworkUrl:          t.ArtworkUrl,
			TagList:             t.TagList,
			PublisherArtist:     t.PublisherArtist,
			SoundCloudUser:      t.SoundCloudUser,
			LocalPath:           t.LocalPath,
			LocalPathBroken:     t.LocalPathBroken,
			RemovedFromPlaylist: t.RemovedFromPlaylist,
		})

		if err != nil {
			tx.Rollback()
			return err
		}
	}

	tx.Commit()

	return nil
}
